image: eclipse-temurin:17-jdk-jammy

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - chmod +x ./gradlew


build_all:
  stage: build
  script:
    - ./gradlew buildAll
  artifacts:
    paths:
      - build/libs/
      - subprojects/**/build/libs/
    expire_in: 1 week


test_all:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit:
        - **/build/test-results/test/*.xml
        - subprojects/**/build/test-results/test/*.xml


deploy_snapshots:
  stage: deploy
  image: eclipse-temurin:17-jdk-jammy
  only:
    - branches
    - merge_requests
  except:
    - tags
  script:
    - ./gradlew publish \
        -PrepoUrl=https://mvn.revived.club/snapshots/ \
        -PrepoUser=$REPOSILITE_USER \
        -PrepoPass=$REPOSILITE_TOKEN


deploy_releases:
  stage: deploy
  image: eclipse-temurin:17-jdk-jammy
  only:
    - tags
  script:
    - ./gradlew publish \
        -PrepoUrl=https://mvn.revived.club/releases/ \
        -PrepoUser=$REPOSILITE_USER \
        -PrepoPass=$REPOSILITE_TOKEN
